/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author IM
 */
public class ReglasAhorcado extends javax.swing.JFrame {

    /**
     * Creates new form ReglasAhorcado
     */
    public ReglasAhorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRules = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRules.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRules.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblRules.setAlignmentX(0.5F);
        lblRules.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRules.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 220));

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, 270));

        lblBG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/img/wood.jpg"))); // NOI18N
        lblBG.setAlignmentX(0.1F);
        lblBG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MyRoom.GoTo("MainMenu");
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        rules();
    }//GEN-LAST:event_formWindowOpened
    Roomer MyRoom = new Roomer();
    
   private void rules(){
      String ru="";
      String arreglo[]= new String [6];
      arreglo[0]="<html>1. El juego brinda una palabra para adivinar.<P>";
      arreglo[1]="<html>2. Se muestra la cantidad de espacio que contiene la palabra.<P>";
      arreglo[2]="<html>3. El jugador va diciendo letras con el fin de completar la palabra.<P>";
      arreglo[3]="<html>4. El jugador solo tiene seis oportunidades para fallar al decir las letras.<P>";
      arreglo[4]="<html>5. Si el jugador acierta una letra se va a mostrar en el su lugar correspondiente.<P>";
      arreglo[5]="<html>6. Si una letra se repite se coloca en todos los espacios en a las que pertecene.<P>";
      
      for(int r=0;r<arreglo.length;r++){
          if(r==0){
              ru=ru+arreglo[0];
          }
          else if(r==1){
              ru=ru+arreglo[1];
          }
          else if(r==2){
              ru=ru+arreglo[2];
          }
          else if(r==3){
              ru=ru+arreglo[3];
          }
          else if(r==4){
              ru=ru+arreglo[4];
          }
          else if(r==5){
              ru=ru+arreglo[5];
          } 
          
      }//fin del for
      lblRules.setText(ru);

   }//fin del método rules
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReglasAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReglasAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReglasAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReglasAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReglasAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblRules;
    // End of variables declaration//GEN-END:variables
}
